
DROP TABLE SEGMENT;
DROP TABLE FFC;
DROP TABLE RESERVATION;
DROP TABLE FARE;
DROP TABLE LEG_INSTANCE;
DROP TABLE FLIGHT_LEG;
DROP TABLE FLIGHT;
DROP TABLE CAN_LAND;
DROP TABLE CUSTOMER;
DROP TABLE AIRPORT;
DROP TABLE AIRPLANE;
DROP TABLE AIRLINE;
DROP TABLE AIRPLANE_TYPE;
DROP TABLE COMPANY;
